/**
 * Students API
 * Students API
 *
 * OpenAPI spec version: 1.1.0-oas3
 * Contact: shankar.nakai@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */



import { StudentClass } from './studentClass';

import { StudentItem } from './studentItem';




export interface StudentDetail extends StudentItem { 

    
    classes: Array<StudentClass>;

}


